# Generated by Django 3.1.7 on 2021-03-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True,  verbose_name='Dodano'),
            preserve_default=False,
        ),
    ]
