# Generated by Django 2.2 on 2021-05-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tweet',
            new_name='post',
        ),
    ]
