# Generated by Django 3.1.7 on 2021-03-23 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210323_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='O mnie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Obserwowani'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images', verbose_name='Zdjęcie'),
        ),
    ]
