# Generated by Django 3.1.7 on 2021-03-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210323_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='O mnie'),
        ),
    ]
